### ISSUE TITLE
Automated request for every statistics API  

### ISSUE THREAD

**Issue by okids** [okids/projekEPL#2]

**Comment by fnugrahendi** [comment]
automated request maksudnya semua parameter disediakan trus kita loop aja gitu kan?

**Comment by okids** [comment]
yoi, kita tinggal ganti endpoint untuk tipe data statistiknya aja tuh. Misalnya / jadi win, lose atau fitur lainnya. Yang %stats% ini : ../ranked/teams/%stats% ganti win, lose, dll.

terus yang "page=0&pageSize=20&compSeasons=54&comps=1&altIds=true"  bagian "compSeasons=xx" nya di ganti jadi 18,19,20 dll. Liat aja endpoint API nya untuk semua seasons
